### PR TITLE
docs: fix jsdoc is not applied for overloading methods

### PR DESCRIPTION
**Pull request by WoodNeck**
## Details
tl;dr;

> before
image

> after
image

### CODE REVIEW

**Review by daybrush — APPROVED** [review]
LGTM

**Comment by WoodNeck** [comment]
I found out that all jsdoc created extending the current Component has the wrong indentation on their documentation.

Here's Flicking's current API documentation
image

Fixed:
image

**Comment by WoodNeck** [comment]
@daybrush 
Sorry, but can you review the latest commit again? 😊

**Comment by daybrush** [comment]
@WoodNeck 
oh good.
Want to get rid of the type once for restparam?

The rest parameter seems to be ambiguous to specify the type.
```
   * @param - Additional parameters when triggering a custom event <ko>커스텀 이벤트가 발생할 때 필요시 추가적으로 전달할 데이터</ko>
```

**Comment by WoodNeck** [comment]
> @WoodNeck
> oh good.
> Want to get rid of the type once for restparam?
> 
> The rest parameter seems to be ambiguous to specify the type.
> 
> ```
>    * @param - Additional parameters when triggering a custom event <ko>커스텀 이벤트가 발생할 때 필요시 추가적으로 전달할 데이터</ko>
> ```

I agree with you. Should I just remove it or can you suggest a better solution?

**Review by mixed — APPROVED** [review]
🚀

**Pull request merged**
