### PR TITLE
fix: trigger not handling all event handlers

### LINKED ISSUE #52: trigger is not handling all handlers when some handlers are removed while calling it
## Description
`trigger` is not handling all handlers when some handlers are removed while calling it.

## Steps to check or reproduce
Use multiple `once` handlers and check whether they are all called by a single trigger().

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#52

## Details
This fixes #52

### CODE REVIEW

**Review by daybrush — APPROVED** [review]
LGTM.

This method is executed even if the next handler is deleted.

However, if it check individually, it will cost a lot of checking.

**Comment by WoodNeck** [comment]
> LGTM.
> 
> This method is executed even if the next handler is deleted.
> 
> However, if it check individually, it will cost a lot of checking.

This fix is for when the previous handler is removed.
image
The simplest representative code might look like the above screenshot,

**Comment by WoodNeck** [comment]
@daybrush 
Of course that's different as I'm representing the previous code...

**Comment by daybrush** [comment]
@WoodNeck 

You are right. The method you said is a good one because it doesn't get any errors.

What I'm talking about is a future problem. Events will continue to be triggered even after the event is released or destroyed.

**Comment by WoodNeck** [comment]
I'm fixing the issue of the handler removing itself here especially by calling `once`, and what you're saying is handlers removing each other.
I think that shouldn't happen, as that's highly dependent on the order of events attached.
And as we don't guarantee event order in any of our code, that's totally the user's fault doing that.
The user simply can bypass it by merging to handlers attached to the same event and conditionally handle them inside.
So IMO, event handlers shouldn't remove each other and it's okay to trigger events even if it's removed before calling them.

**Pull request merged**
